package xtend_templates.rubyonrails;

import com.google.common.base.Objects;
import inflector.Inflector;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import main.Project;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import structure.domain_model.Attribute;
import structure.domain_model.DomainModel;
import structure.domain_model.Entity;
import structure.user_interface.ActionAIO;
import structure.user_interface.ActionAIONavigation;
import structure.user_interface.ActionAIOOperation;
import structure.user_interface.ActionAIOOperationType;
import structure.user_interface.DataAIO;
import structure.user_interface.DataAIOType;
import structure.user_interface.InteractionBlock;
import structure.user_interface.InteractionBlockType;
import structure.user_interface.InteractionSpace;
import structure.user_interface.Menu;
import structure.user_interface.MenuBar;
import structure.user_interface.MenuItem;

@SuppressWarnings("all")
public class RubyScriptTemplate {
  private final String controllerName = "pages";
  
  private Project project;
  
  public CharSequence generate(final Project project) {
    this.project = project;
    return this.template();
  }
  
  public CharSequence template() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Generated by Amalia Code Generator");
    _builder.newLine();
    _builder.append("# Here we are removing the Gemfile and starting over");
    _builder.newLine();
    _builder.append("remove_file \"Gemfile\"");
    _builder.newLine();
    _builder.append("run \"touch Gemfile\"");
    _builder.newLine();
    _builder.append("# be sure to add source at the top of the file");
    _builder.newLine();
    _builder.append("add_source \'https://rubygems.org\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("gem \'rails\', \'4.2.4\'");
    _builder.newLine();
    _builder.append("gem \'sqlite3\'");
    _builder.newLine();
    _builder.append("gem \'sass-rails\', \'~> 5.0\'");
    _builder.newLine();
    _builder.append("gem \'uglifier\', \'>= 1.3.0\'");
    _builder.newLine();
    _builder.append("gem \'coffee-rails\', \'~> 4.1.0\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("gem \'jquery-rails\'");
    _builder.newLine();
    _builder.append("gem \'turbolinks\'");
    _builder.newLine();
    _builder.append("gem \'jbuilder\', \'~> 2.0\'");
    _builder.newLine();
    _builder.append("gem \'sdoc\', \'~> 0.4.0\'");
    _builder.newLine();
    _builder.append("gem_group :development, :test do");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gem \'byebug\'");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("gem_group :development do");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gem \'web-console\', \'~> 2.0\'");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("gem \'spring\'");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("gem \'bootstrap-sass\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("gem \'simple_form\'");
    _builder.newLine();
    _builder.append("gem \'rails_layout\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# run \'spring stop\'");
    _builder.newLine();
    _builder.append("run \'bundle install\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# instala um layout generico do bootstrap");
    _builder.newLine();
    _builder.append("generate \'layout:install bootstrap3 --force\'");
    _builder.newLine();
    _builder.append("# instala o simple_form usando o bootstrap");
    _builder.newLine();
    _builder.append("generate \'simple_form:install --bootstrap --force\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# ativa as validacoes do html5 nas paginas");
    _builder.newLine();
    _builder.append("comment_lines \'config/initializers/simple_form.rb\', /config.browser_validations = false/");
    _builder.newLine();
    _builder.append("insert_into_file \'config/initializers/simple_form.rb\', :after => /# config.browser_validations = false/ do <<-TEXT");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    _builder.append("config.browser_validations = true");
    _builder.newLine();
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end\t");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# Scaffold all controllers models views");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# Pluralized names variables");
    _builder.newLine();
    {
      DomainModel _domainModel = this.project.getDomainModel();
      HashMap<String, Entity> _entities = _domainModel.getEntities();
      Collection<Entity> _values = _entities.values();
      for(final Entity e : _values) {
        String _name = e.getName();
        String _lowerCase = _name.toLowerCase();
        _builder.append(_lowerCase, "");
        _builder.append(" = \"");
        String _name_1 = e.getName();
        String _lowerCase_1 = _name_1.toLowerCase();
        _builder.append(_lowerCase_1, "");
        _builder.append("\".pluralize");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    _builder.append("# Model and Scaffold");
    _builder.newLine();
    {
      DomainModel _domainModel_1 = this.project.getDomainModel();
      HashMap<String, Entity> _entities_1 = _domainModel_1.getEntities();
      Collection<Entity> _values_1 = _entities_1.values();
      for(final Entity e_1 : _values_1) {
        {
          boolean _hasReferenceAttributes = e_1.hasReferenceAttributes();
          boolean _not = (!_hasReferenceAttributes);
          if (_not) {
            _builder.append("generate(:model, \"");
            String _name_2 = e_1.getName();
            String _lowerCase_2 = _name_2.toLowerCase();
            _builder.append(_lowerCase_2, "");
            _builder.append(" ");
            {
              ArrayList<Attribute> _attributes = e_1.getAttributes();
              for(final Attribute attr : _attributes) {
                _builder.append(" ");
                String _name_3 = attr.getName();
                String _lowerCase_3 = _name_3.toLowerCase();
                _builder.append(_lowerCase_3, "");
                _builder.append(":");
                String _type = attr.getType();
                String _lowerCase_4 = _type.toLowerCase();
                String _dataType = this.getDataType(_lowerCase_4);
                _builder.append(_dataType, "");
              }
            }
            _builder.append("\")");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("generate(:scaffold, \"");
        String _name_4 = e_1.getName();
        String _lowerCase_5 = _name_4.toLowerCase();
        _builder.append(_lowerCase_5, "");
        _builder.append(" ");
        {
          ArrayList<Attribute> _attributes_1 = e_1.getAttributes();
          for(final Attribute attr_1 : _attributes_1) {
            _builder.append(" ");
            String _name_5 = attr_1.getName();
            String _lowerCase_6 = _name_5.toLowerCase();
            _builder.append(_lowerCase_6, "");
            _builder.append(":");
            String _type_1 = attr_1.getType();
            String _lowerCase_7 = _type_1.toLowerCase();
            String _dataType_1 = this.getDataType(_lowerCase_7);
            _builder.append(_dataType_1, "");
          }
        }
        _builder.append("\")");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    CharSequence _updateApplicationFile = this.updateApplicationFile();
    _builder.append(_updateApplicationFile, "");
    _builder.newLineIfNotEmpty();
    CharSequence _createMenu = this.createMenu();
    _builder.append(_createMenu, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("#rotas");
    _builder.newLine();
    _builder.append("remove_file \'config/routes.rb\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("create_file \'config/routes.rb\' do <<-TEXT");
    _builder.newLine();
    _builder.append("Rails.application.routes.draw do");
    _builder.newLine();
    {
      DomainModel _domainModel_2 = this.project.getDomainModel();
      HashMap<String, Entity> _entities_2 = _domainModel_2.getEntities();
      Collection<Entity> _values_2 = _entities_2.values();
      for(final Entity e_2 : _values_2) {
        _builder.append("resources :#{");
        String _name_6 = e_2.getName();
        String _lowerCase_8 = _name_6.toLowerCase();
        _builder.append(_lowerCase_8, "");
        _builder.append("}");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      InteractionSpace _mainInteractionSpace = this.project.getMainInteractionSpace();
      boolean _notEquals = (!Objects.equal(_mainInteractionSpace, null));
      if (_notEquals) {
        _builder.append("root \'");
        _builder.append(this.controllerName, "");
        _builder.append("#");
        InteractionSpace _mainInteractionSpace_1 = this.project.getMainInteractionSpace();
        String _name_7 = _mainInteractionSpace_1.getName();
        String _lowerCase_9 = _name_7.toLowerCase();
        _builder.append(_lowerCase_9, "");
        _builder.append("\'");
        _builder.newLineIfNotEmpty();
      } else {
        _builder.append("root \'#{");
        DomainModel _domainModel_3 = this.project.getDomainModel();
        HashMap<String, Entity> _entities_3 = _domainModel_3.getEntities();
        Collection<Entity> _values_3 = _entities_3.values();
        Entity _get = ((Entity[])Conversions.unwrapArray(_values_3, Entity.class))[0];
        String _name_8 = _get.getName();
        String _lowerCase_10 = _name_8.toLowerCase();
        _builder.append(_lowerCase_10, "");
        _builder.append("}#index\'");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("end");
    _builder.newLine();
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.append("# Cria o controlador e página IMPORTANTE");
    _builder.newLine();
    _builder.append("generate(:controller, \"");
    String _firstUpper = StringExtensions.toFirstUpper(this.controllerName);
    _builder.append(_firstUpper, "");
    HashMap<String, InteractionSpace> _interactionSpaces = this.project.getInteractionSpaces();
    Collection<InteractionSpace> _values_4 = _interactionSpaces.values();
    String _pagesNames = this.getPagesNames(_values_4);
    _builder.append(_pagesNames, "");
    _builder.append("\")");
    _builder.newLineIfNotEmpty();
    _builder.append("remove_file \'app/controllers/");
    _builder.append(this.controllerName, "");
    _builder.append("_controller.rb\'");
    _builder.newLineIfNotEmpty();
    _builder.append("create_file \'app/controllers/");
    _builder.append(this.controllerName, "");
    _builder.append("_controller.rb\' do <<-TEXT");
    _builder.newLineIfNotEmpty();
    _builder.append("class ");
    String _firstUpper_1 = StringExtensions.toFirstUpper(this.controllerName);
    _builder.append(_firstUpper_1, "");
    _builder.append("Controller < ApplicationController");
    _builder.newLineIfNotEmpty();
    {
      HashMap<String, InteractionSpace> _interactionSpaces_1 = this.project.getInteractionSpaces();
      Collection<InteractionSpace> _values_5 = _interactionSpaces_1.values();
      for(final InteractionSpace is : _values_5) {
        _builder.append("def ");
        String _name_9 = is.getName();
        String _lowerCase_11 = _name_9.toLowerCase();
        _builder.append(_lowerCase_11, "");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("@title = \"");
        String _text = is.getText();
        String _lowerCase_12 = _text.toLowerCase();
        String _firstUpper_2 = StringExtensions.toFirstUpper(_lowerCase_12);
        _builder.append(_firstUpper_2, "\t");
        _builder.append("\"");
        _builder.newLineIfNotEmpty();
        {
          ArrayList<InteractionBlock> _interactionBlocks = is.getInteractionBlocks();
          for(final InteractionBlock ib : _interactionBlocks) {
            {
              InteractionBlockType _interactionBlockType = ib.getInteractionBlockType();
              boolean _equals = Objects.equal(_interactionBlockType, InteractionBlockType.ViewList);
              if (_equals) {
                _builder.append("@#{");
                Entity _entity = ib.getEntity();
                String _name_10 = _entity.getName();
                String _lowerCase_13 = _name_10.toLowerCase();
                _builder.append(_lowerCase_13, "");
                _builder.append("} = ");
                Entity _entity_1 = ib.getEntity();
                String _name_11 = _entity_1.getName();
                String _lowerCase_14 = _name_11.toLowerCase();
                String _firstUpper_3 = StringExtensions.toFirstUpper(_lowerCase_14);
                _builder.append(_firstUpper_3, "");
                _builder.append(".all");
                _builder.newLineIfNotEmpty();
              } else {
                InteractionBlockType _interactionBlockType_1 = ib.getInteractionBlockType();
                boolean _equals_1 = Objects.equal(_interactionBlockType_1, InteractionBlockType.ViewEntity);
                if (_equals_1) {
                  _builder.append("@new_");
                  Entity _entity_2 = ib.getEntity();
                  String _name_12 = _entity_2.getName();
                  String _lowerCase_15 = _name_12.toLowerCase();
                  _builder.append(_lowerCase_15, "");
                  _builder.append(" = ");
                  Entity _entity_3 = is.getEntity();
                  String _name_13 = _entity_3.getName();
                  String _firstUpper_4 = StringExtensions.toFirstUpper(_name_13);
                  _builder.append(_firstUpper_4, "");
                  _builder.append(".new");
                  _builder.newLineIfNotEmpty();
                  {
                    boolean _and = false;
                    ArrayList<ActionAIO> _actionAIOs = ib.getActionAIOs();
                    int _size = _actionAIOs.size();
                    boolean _greaterThan = (_size > 0);
                    if (!_greaterThan) {
                      _and = false;
                    } else {
                      ActionAIOOperationType _hasUpdateOrCreateOp = this.hasUpdateOrCreateOp(ib);
                      boolean _notEquals_1 = (!Objects.equal(_hasUpdateOrCreateOp, null));
                      _and = _notEquals_1;
                    }
                    if (_and) {
                      ActionAIOOperationType aioOp = this.hasUpdateOrCreateOp(ib);
                      _builder.newLineIfNotEmpty();
                      {
                        boolean _equals_2 = Objects.equal(aioOp, ActionAIOOperationType.CallUpdateOp);
                        if (_equals_2) {
                          _builder.append("@instance_");
                          Entity _entity_4 = ib.getEntity();
                          String _name_14 = _entity_4.getName();
                          String _lowerCase_16 = _name_14.toLowerCase();
                          _builder.append(_lowerCase_16, "");
                          _builder.append(" = ");
                          Entity _entity_5 = ib.getEntity();
                          String _name_15 = _entity_5.getName();
                          String _firstUpper_5 = StringExtensions.toFirstUpper(_name_15);
                          _builder.append(_firstUpper_5, "");
                          _builder.append(".find(params[:param])");
                          _builder.newLineIfNotEmpty();
                        }
                      }
                    } else {
                      _builder.append("@instance_");
                      Entity _entity_6 = ib.getEntity();
                      String _name_16 = _entity_6.getName();
                      String _lowerCase_17 = _name_16.toLowerCase();
                      _builder.append(_lowerCase_17, "");
                      _builder.append(" = ");
                      Entity _entity_7 = ib.getEntity();
                      String _name_17 = _entity_7.getName();
                      String _firstUpper_6 = StringExtensions.toFirstUpper(_name_17);
                      _builder.append(_firstUpper_6, "");
                      _builder.append(".find(params[:param])");
                      _builder.newLineIfNotEmpty();
                    }
                  }
                } else {
                  InteractionBlockType _interactionBlockType_2 = ib.getInteractionBlockType();
                  boolean _equals_3 = Objects.equal(_interactionBlockType_2, InteractionBlockType.ViewRelatedList);
                  if (_equals_3) {
                    {
                      Entity _entity_8 = ib.getEntity();
                      Entity _entity_9 = is.getEntity();
                      String _name_18 = _entity_9.getName();
                      String _lowerCase_18 = _name_18.toLowerCase();
                      Attribute _attributeByNameIgnoreCase = _entity_8.getAttributeByNameIgnoreCase(_lowerCase_18);
                      boolean _notEquals_2 = (!Objects.equal(_attributeByNameIgnoreCase, null));
                      if (_notEquals_2) {
                        _builder.append("@list_");
                        Entity _entity_10 = ib.getEntity();
                        String _name_19 = _entity_10.getName();
                        String _lowerCase_19 = _name_19.toLowerCase();
                        _builder.append(_lowerCase_19, "");
                        _builder.append(" = ");
                        Entity _entity_11 = ib.getEntity();
                        String _name_20 = _entity_11.getName();
                        String _lowerCase_20 = _name_20.toLowerCase();
                        String _firstUpper_7 = StringExtensions.toFirstUpper(_lowerCase_20);
                        _builder.append(_firstUpper_7, "");
                        _builder.append(".where(");
                        Entity _entity_12 = is.getEntity();
                        String _name_21 = _entity_12.getName();
                        String _lowerCase_21 = _name_21.toLowerCase();
                        _builder.append(_lowerCase_21, "");
                        _builder.append("_id:params[:param])");
                        _builder.newLineIfNotEmpty();
                      } else {
                        _builder.append("@list_");
                        Entity _entity_13 = ib.getEntity();
                        String _name_22 = _entity_13.getName();
                        String _lowerCase_22 = _name_22.toLowerCase();
                        _builder.append(_lowerCase_22, "");
                        _builder.append(" = ");
                        Entity _entity_14 = ib.getEntity();
                        String _name_23 = _entity_14.getName();
                        String _lowerCase_23 = _name_23.toLowerCase();
                        String _firstUpper_8 = StringExtensions.toFirstUpper(_lowerCase_23);
                        _builder.append(_firstUpper_8, "");
                        _builder.append(".where(id:@instance_");
                        Entity _entity_15 = is.getEntity();
                        String _name_24 = _entity_15.getName();
                        String _lowerCase_24 = _name_24.toLowerCase();
                        _builder.append(_lowerCase_24, "");
                        _builder.append(".");
                        Entity _entity_16 = ib.getEntity();
                        String _name_25 = _entity_16.getName();
                        String _lowerCase_25 = _name_25.toLowerCase();
                        _builder.append(_lowerCase_25, "");
                        _builder.append("_id)");
                        _builder.newLineIfNotEmpty();
                      }
                    }
                  } else {
                    InteractionBlockType _interactionBlockType_3 = ib.getInteractionBlockType();
                    boolean _equals_4 = Objects.equal(_interactionBlockType_3, InteractionBlockType.ViewRelatedEntity);
                    if (_equals_4) {
                      {
                        Entity _entity_17 = ib.getEntity();
                        Entity _entity_18 = is.getEntity();
                        String _name_26 = _entity_18.getName();
                        String _lowerCase_26 = _name_26.toLowerCase();
                        Attribute _attributeByNameIgnoreCase_1 = _entity_17.getAttributeByNameIgnoreCase(_lowerCase_26);
                        boolean _notEquals_3 = (!Objects.equal(_attributeByNameIgnoreCase_1, null));
                        if (_notEquals_3) {
                          _builder.append("@list_");
                          Entity _entity_19 = ib.getEntity();
                          String _name_27 = _entity_19.getName();
                          String _lowerCase_27 = _name_27.toLowerCase();
                          _builder.append(_lowerCase_27, "");
                          _builder.append(" = ");
                          Entity _entity_20 = ib.getEntity();
                          String _name_28 = _entity_20.getName();
                          String _lowerCase_28 = _name_28.toLowerCase();
                          String _firstUpper_9 = StringExtensions.toFirstUpper(_lowerCase_28);
                          _builder.append(_firstUpper_9, "");
                          _builder.append(".where(");
                          Entity _entity_21 = is.getEntity();
                          String _name_29 = _entity_21.getName();
                          String _lowerCase_29 = _name_29.toLowerCase();
                          _builder.append(_lowerCase_29, "");
                          _builder.append("_id:params[:param])");
                          _builder.newLineIfNotEmpty();
                        } else {
                          _builder.append("@list_");
                          Entity _entity_22 = ib.getEntity();
                          String _name_30 = _entity_22.getName();
                          String _lowerCase_30 = _name_30.toLowerCase();
                          _builder.append(_lowerCase_30, "");
                          _builder.append(" = ");
                          Entity _entity_23 = ib.getEntity();
                          String _name_31 = _entity_23.getName();
                          String _lowerCase_31 = _name_31.toLowerCase();
                          String _firstUpper_10 = StringExtensions.toFirstUpper(_lowerCase_31);
                          _builder.append(_firstUpper_10, "");
                          _builder.append(".where(id:@instance_");
                          Entity _entity_24 = is.getEntity();
                          String _name_32 = _entity_24.getName();
                          String _lowerCase_32 = _name_32.toLowerCase();
                          _builder.append(_lowerCase_32, "");
                          _builder.append(".");
                          Entity _entity_25 = ib.getEntity();
                          String _name_33 = _entity_25.getName();
                          String _lowerCase_33 = _name_33.toLowerCase();
                          _builder.append(_lowerCase_33, "");
                          _builder.append("_id)");
                          _builder.newLineIfNotEmpty();
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        _builder.append("end");
        _builder.newLine();
      }
    }
    _builder.append("end");
    _builder.newLine();
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    {
      HashMap<String, InteractionSpace> _interactionSpaces_2 = this.project.getInteractionSpaces();
      Collection<InteractionSpace> _values_6 = _interactionSpaces_2.values();
      for(final InteractionSpace is_1 : _values_6) {
        ArrayList<InteractionBlock> _interactionBlocks_1 = is_1.getInteractionBlocks();
        CharSequence _text_1 = this.toText(_interactionBlocks_1, is_1);
        _builder.append(_text_1, "");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.newLine();
    CharSequence _changeOriginalForm = this.changeOriginalForm();
    _builder.append(_changeOriginalForm, "");
    _builder.newLineIfNotEmpty();
    CharSequence _changeOriginalIndex = this.changeOriginalIndex();
    _builder.append(_changeOriginalIndex, "");
    _builder.newLineIfNotEmpty();
    CharSequence _changeOriginalShow = this.changeOriginalShow();
    _builder.append(_changeOriginalShow, "");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("rake \"db:migrate\"");
    _builder.newLine();
    return _builder;
  }
  
  public String getDataType(final String type) {
    String output = "string";
    switch (type) {
      case "references":
        output = "references";
        break;
      case "int":
        output = "integer";
        break;
      case "number":
        output = "integer";
        break;
      case "numeric":
        output = "integer";
        break;
      case "integer":
        output = "integer";
        break;
      case "date":
        output = "date";
        break;
      default:
        output = "string";
        break;
    }
    return output;
  }
  
  public CharSequence changeOriginalShow() {
    StringConcatenation _builder = new StringConcatenation();
    {
      DomainModel _domainModel = this.project.getDomainModel();
      HashMap<String, Entity> _entities = _domainModel.getEntities();
      Collection<Entity> _values = _entities.values();
      for(final Entity e : _values) {
        {
          List<Attribute> _referencedAttributes = e.referencedAttributes();
          int _size = _referencedAttributes.size();
          boolean _greaterThan = (_size > 0);
          if (_greaterThan) {
            _builder.append("remove_file \'app/views/");
            String _name = e.getName();
            String _lowerCase = _name.toLowerCase();
            String _plural = Inflector.plural(_lowerCase);
            _builder.append(_plural, "");
            _builder.append("/show.html.erb\'");
            _builder.newLineIfNotEmpty();
            _builder.append("create_file \'app/views/");
            String _name_1 = e.getName();
            String _lowerCase_1 = _name_1.toLowerCase();
            String _plural_1 = Inflector.plural(_lowerCase_1);
            _builder.append(_plural_1, "");
            _builder.append("/show.html.erb\' do <<-TEXT\t\t");
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            _builder.append("<p id=\"notice\"><%= notice %></p>");
            _builder.newLine();
            {
              ArrayList<Attribute> _attributes = e.getAttributes();
              for(final Attribute attr : _attributes) {
                {
                  Boolean _isReference = attr.isReference();
                  if ((_isReference).booleanValue()) {
                    DomainModel _domainModel_1 = this.project.getDomainModel();
                    String _name_2 = attr.getName();
                    Entity associatedEntity = _domainModel_1.getEntityByName(_name_2);
                    _builder.newLineIfNotEmpty();
                    List<Attribute> entityAttributes = associatedEntity.getAttributes();
                    _builder.newLineIfNotEmpty();
                    _builder.append("<p>");
                    _builder.newLine();
                    _builder.append("  \t");
                    _builder.append("<strong>");
                    String _name_3 = attr.getName();
                    String _firstUpper = StringExtensions.toFirstUpper(_name_3);
                    _builder.append(_firstUpper, "  \t");
                    _builder.append(":</strong>");
                    _builder.newLineIfNotEmpty();
                    _builder.append("  \t");
                    _builder.append("<%= @");
                    String _name_4 = e.getName();
                    String _lowerCase_2 = _name_4.toLowerCase();
                    _builder.append(_lowerCase_2, "  \t");
                    _builder.append(".");
                    String _name_5 = attr.getName();
                    String _lowerCase_3 = _name_5.toLowerCase();
                    _builder.append(_lowerCase_3, "  \t");
                    _builder.append(".");
                    Attribute _get = entityAttributes.get(0);
                    String _name_6 = _get.getName();
                    String _lowerCase_4 = _name_6.toLowerCase();
                    _builder.append(_lowerCase_4, "  \t");
                    _builder.append(" %>");
                    _builder.newLineIfNotEmpty();
                    _builder.append("</p>");
                    _builder.newLine();
                  } else {
                    _builder.append("<p>");
                    _builder.newLine();
                    _builder.append("\t");
                    _builder.append("<strong>");
                    String _name_7 = attr.getName();
                    String _firstUpper_1 = StringExtensions.toFirstUpper(_name_7);
                    _builder.append(_firstUpper_1, "\t");
                    _builder.append(":</strong>");
                    _builder.newLineIfNotEmpty();
                    _builder.append("  \t");
                    _builder.append("<%= @");
                    String _name_8 = e.getName();
                    String _lowerCase_5 = _name_8.toLowerCase();
                    _builder.append(_lowerCase_5, "  \t");
                    _builder.append(".");
                    String _name_9 = attr.getName();
                    String _lowerCase_6 = _name_9.toLowerCase();
                    _builder.append(_lowerCase_6, "  \t");
                    _builder.append(" %>");
                    _builder.newLineIfNotEmpty();
                    _builder.append("</p>");
                    _builder.newLine();
                  }
                }
              }
            }
            _builder.append("\t");
            _builder.append("<%= link_to \'Edit\', edit_");
            String _name_10 = e.getName();
            String _lowerCase_7 = _name_10.toLowerCase();
            _builder.append(_lowerCase_7, "\t");
            _builder.append("_path(@");
            String _name_11 = e.getName();
            String _lowerCase_8 = _name_11.toLowerCase();
            _builder.append(_lowerCase_8, "\t");
            _builder.append(") %> |");
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            _builder.append("<%= link_to \'Back\', #{");
            String _name_12 = e.getName();
            String _lowerCase_9 = _name_12.toLowerCase();
            _builder.append(_lowerCase_9, "\t");
            _builder.append("}_path %>");
            _builder.newLineIfNotEmpty();
            _builder.append("TEXT");
            _builder.newLine();
            _builder.append("end");
            _builder.newLine();
          }
        }
      }
    }
    return _builder;
  }
  
  public CharSequence changeOriginalIndex() {
    StringConcatenation _builder = new StringConcatenation();
    {
      DomainModel _domainModel = this.project.getDomainModel();
      HashMap<String, Entity> _entities = _domainModel.getEntities();
      Collection<Entity> _values = _entities.values();
      for(final Entity e : _values) {
        {
          List<Attribute> _referencedAttributes = e.referencedAttributes();
          int _size = _referencedAttributes.size();
          boolean _greaterThan = (_size > 0);
          if (_greaterThan) {
            _builder.append("remove_file \'app/views/");
            String _name = e.getName();
            String _lowerCase = _name.toLowerCase();
            String _plural = Inflector.plural(_lowerCase);
            _builder.append(_plural, "");
            _builder.append("/index.html.erb\'");
            _builder.newLineIfNotEmpty();
            _builder.append("create_file \'app/views/");
            String _name_1 = e.getName();
            String _lowerCase_1 = _name_1.toLowerCase();
            String _plural_1 = Inflector.plural(_lowerCase_1);
            _builder.append(_plural_1, "");
            _builder.append("/index.html.erb\' do <<-TEXT");
            _builder.newLineIfNotEmpty();
            _builder.append("<p id=\"notice\"><%= notice %></p>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("<h1>Listing #{");
            String _name_2 = e.getName();
            String _lowerCase_2 = _name_2.toLowerCase();
            _builder.append(_lowerCase_2, "");
            _builder.append("}</h1>");
            _builder.newLineIfNotEmpty();
            _builder.newLine();
            _builder.append("<table>");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<thead>");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("<tr>");
            _builder.newLine();
            {
              ArrayList<Attribute> _attributes = e.getAttributes();
              for(final Attribute attr : _attributes) {
                _builder.append("   ");
                _builder.append("<th>");
                String _name_3 = attr.getName();
                String _firstUpper = StringExtensions.toFirstUpper(_name_3);
                _builder.append(_firstUpper, "   ");
                _builder.append("</th>");
                _builder.newLineIfNotEmpty();
              }
            }
            _builder.append("      ");
            _builder.append("<th colspan=\"3\"></th>");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("</tr>");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("</thead>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<tbody>");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("<% @#{");
            String _name_4 = e.getName();
            String _lowerCase_3 = _name_4.toLowerCase();
            _builder.append(_lowerCase_3, "    ");
            _builder.append("}.each do |");
            String _name_5 = e.getName();
            String _lowerCase_4 = _name_5.toLowerCase();
            _builder.append(_lowerCase_4, "    ");
            _builder.append("| %>");
            _builder.newLineIfNotEmpty();
            _builder.append("      ");
            _builder.append("<tr>");
            _builder.newLine();
            {
              ArrayList<Attribute> _attributes_1 = e.getAttributes();
              for(final Attribute attr_1 : _attributes_1) {
                {
                  Boolean _isReference = attr_1.isReference();
                  if ((_isReference).booleanValue()) {
                    DomainModel _domainModel_1 = this.project.getDomainModel();
                    String _name_6 = attr_1.getName();
                    Entity associatedEntity = _domainModel_1.getEntityByName(_name_6);
                    _builder.newLineIfNotEmpty();
                    List<Attribute> entityAttributes = associatedEntity.getAttributes();
                    _builder.newLineIfNotEmpty();
                    _builder.append("\t\t      \t\t\t");
                    _builder.append("<td><%= ");
                    String _name_7 = e.getName();
                    String _lowerCase_5 = _name_7.toLowerCase();
                    _builder.append(_lowerCase_5, "\t\t      \t\t\t");
                    _builder.append(".");
                    String _name_8 = attr_1.getName();
                    String _lowerCase_6 = _name_8.toLowerCase();
                    _builder.append(_lowerCase_6, "\t\t      \t\t\t");
                    _builder.append(".");
                    Attribute _get = entityAttributes.get(0);
                    String _name_9 = _get.getName();
                    String _lowerCase_7 = _name_9.toLowerCase();
                    _builder.append(_lowerCase_7, "\t\t      \t\t\t");
                    _builder.append(" %></td>");
                    _builder.newLineIfNotEmpty();
                  } else {
                    _builder.append("\t\t      \t");
                    _builder.append("<td><%= ");
                    String _name_10 = e.getName();
                    String _lowerCase_8 = _name_10.toLowerCase();
                    _builder.append(_lowerCase_8, "\t\t      \t");
                    _builder.append(".");
                    String _name_11 = attr_1.getName();
                    String _lowerCase_9 = _name_11.toLowerCase();
                    _builder.append(_lowerCase_9, "\t\t      \t");
                    _builder.append(" %></td>");
                    _builder.newLineIfNotEmpty();
                  }
                }
              }
            }
            _builder.append("        ");
            _builder.append("<td><%= link_to \'Show\', ");
            String _name_12 = e.getName();
            String _lowerCase_10 = _name_12.toLowerCase();
            _builder.append(_lowerCase_10, "        ");
            _builder.append(" %></td>");
            _builder.newLineIfNotEmpty();
            _builder.append("        ");
            _builder.append("<td><%= link_to \'Edit\', edit_");
            String _name_13 = e.getName();
            String _lowerCase_11 = _name_13.toLowerCase();
            _builder.append(_lowerCase_11, "        ");
            _builder.append("_path(");
            String _name_14 = e.getName();
            String _lowerCase_12 = _name_14.toLowerCase();
            _builder.append(_lowerCase_12, "        ");
            _builder.append(") %></td>");
            _builder.newLineIfNotEmpty();
            _builder.append("        ");
            _builder.append("<td><%= link_to \'Destroy\', ");
            String _name_15 = e.getName();
            String _lowerCase_13 = _name_15.toLowerCase();
            _builder.append(_lowerCase_13, "        ");
            _builder.append(", method: :delete, data: { confirm: \'Are you sure?\' } %></td>");
            _builder.newLineIfNotEmpty();
            _builder.append("      ");
            _builder.append("</tr>");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("<% end %>");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("</tbody>");
            _builder.newLine();
            _builder.append("</table>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("<br>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("<%= link_to \'New ");
            String _name_16 = e.getName();
            String _firstUpper_1 = StringExtensions.toFirstUpper(_name_16);
            _builder.append(_firstUpper_1, "");
            _builder.append("\', new_");
            String _name_17 = e.getName();
            String _lowerCase_14 = _name_17.toLowerCase();
            _builder.append(_lowerCase_14, "");
            _builder.append("_path %>");
            _builder.newLineIfNotEmpty();
            _builder.append("TEXT");
            _builder.newLine();
            _builder.append("end");
            _builder.newLine();
          }
        }
      }
    }
    return _builder;
  }
  
  public CharSequence changeOriginalForm() {
    StringConcatenation _builder = new StringConcatenation();
    {
      DomainModel _domainModel = this.project.getDomainModel();
      HashMap<String, Entity> _entities = _domainModel.getEntities();
      Collection<Entity> _values = _entities.values();
      for(final Entity e : _values) {
        {
          List<Attribute> _referencedAttributes = e.referencedAttributes();
          int _size = _referencedAttributes.size();
          boolean _greaterThan = (_size > 0);
          if (_greaterThan) {
            _builder.append("remove_file \'app/views/");
            String _name = e.getName();
            String _lowerCase = _name.toLowerCase();
            String _plural = Inflector.plural(_lowerCase);
            _builder.append(_plural, "");
            _builder.append("/_form.html.erb\'");
            _builder.newLineIfNotEmpty();
            _builder.append("create_file \'app/views/");
            String _name_1 = e.getName();
            String _lowerCase_1 = _name_1.toLowerCase();
            String _plural_1 = Inflector.plural(_lowerCase_1);
            _builder.append(_plural_1, "");
            _builder.append("/_form.html.erb\' do <<-TEXT");
            _builder.newLineIfNotEmpty();
            _builder.append("<%= simple_form_for(@");
            String _name_2 = e.getName();
            String _lowerCase_2 = _name_2.toLowerCase();
            _builder.append(_lowerCase_2, "");
            _builder.append(") do |f| %>");
            _builder.newLineIfNotEmpty();
            _builder.append("  ");
            _builder.append("<%= f.error_notification %>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<div class=\"form-inputs\">");
            _builder.newLine();
            {
              ArrayList<Attribute> _attributes = e.getAttributes();
              for(final Attribute attr : _attributes) {
                {
                  Boolean _isReference = attr.isReference();
                  if ((_isReference).booleanValue()) {
                    DomainModel _domainModel_1 = this.project.getDomainModel();
                    String _name_3 = attr.getName();
                    Entity associatedEntity = _domainModel_1.getEntityByName(_name_3);
                    _builder.newLineIfNotEmpty();
                    List<Attribute> entityAttributes = associatedEntity.getAttributes();
                    _builder.newLineIfNotEmpty();
                    _builder.append("<%= f.association :");
                    String _name_4 = attr.getName();
                    String _lowerCase_3 = _name_4.toLowerCase();
                    _builder.append(_lowerCase_3, "");
                    _builder.append(",label_method: :");
                    Attribute _get = entityAttributes.get(0);
                    String _name_5 = _get.getName();
                    String _lowerCase_4 = _name_5.toLowerCase();
                    _builder.append(_lowerCase_4, "");
                    _builder.append(", required:true %>");
                    _builder.newLineIfNotEmpty();
                  } else {
                    _builder.append("  ");
                    _builder.append("<%= f.input :");
                    String _name_6 = attr.getName();
                    String _lowerCase_5 = _name_6.toLowerCase();
                    _builder.append(_lowerCase_5, "  ");
                    _builder.append(" %>");
                    _builder.newLineIfNotEmpty();
                  }
                }
              }
            }
            _builder.append("  ");
            _builder.append("</div>");
            _builder.newLine();
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<div class=\"form-actions\">");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("<%= f.button :submit %>");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("</div>");
            _builder.newLine();
            _builder.append("<% end %>");
            _builder.newLine();
            _builder.append("TEXT");
            _builder.newLine();
            _builder.append("end");
            _builder.newLine();
          }
        }
      }
    }
    return _builder;
  }
  
  public CharSequence toText(final List<InteractionBlock> interactionBlocks, final InteractionSpace parent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# INTERACTION SPACE: ");
    String _name = parent.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "");
    _builder.newLineIfNotEmpty();
    _builder.append("remove_file \'app/views/");
    _builder.append(this.controllerName, "");
    _builder.append("/");
    String _name_1 = parent.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "");
    _builder.append(".html.erb\'");
    _builder.newLineIfNotEmpty();
    _builder.append("create_file \'app/views/");
    _builder.append(this.controllerName, "");
    _builder.append("/");
    String _name_2 = parent.getName();
    String _lowerCase_2 = _name_2.toLowerCase();
    _builder.append(_lowerCase_2, "");
    _builder.append(".html.erb\' do <<-TEXT");
    _builder.newLineIfNotEmpty();
    _builder.append("<p id=\"notice\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<%= notice %>");
    _builder.newLine();
    _builder.append("</p>");
    _builder.newLine();
    {
      for(final InteractionBlock ib : interactionBlocks) {
        CharSequence _switchResult = null;
        InteractionBlockType _interactionBlockType = ib.getInteractionBlockType();
        if (_interactionBlockType != null) {
          switch (_interactionBlockType) {
            case ViewEntity:
              _switchResult = this.viewEntity(ib, parent);
              break;
            case ViewList:
              _switchResult = this.viewList(ib, parent);
              break;
            case ViewListS:
              _switchResult = this.viewList(ib, parent);
              break;
            case ViewRelatedEntity:
              _switchResult = this.viewRelatedEntity(ib, parent);
              break;
            case ViewRelatedList:
              _switchResult = this.viewRelatedList(ib, parent);
              break;
            case ViewRelatedListS:
              _switchResult = this.viewRelatedList(ib, parent);
              break;
            default:
              break;
          }
        }
        _builder.append(_switchResult, "");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end\t");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence viewRelatedEntity(final InteractionBlock ib, final InteractionSpace parent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<h3>");
    String _text = ib.getText();
    _builder.append(_text, "");
    _builder.append("</h3>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<table style=\"width:100%; border:1px solid;\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs = ib.getDataAIOs();
      for(final DataAIO d : _dataAIOs) {
        _builder.append("    \t");
        _builder.append("<th>");
        String _text_1 = d.getText();
        String _firstUpper = StringExtensions.toFirstUpper(_text_1);
        _builder.append(_firstUpper, "    \t");
        _builder.append("</th>");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("      \t\t");
    _builder.append("<th colspan=\"");
    ArrayList<ActionAIO> _actionAIOs = ib.getActionAIOs();
    int _size = _actionAIOs.size();
    _builder.append(_size, "      \t\t");
    _builder.append("\"></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("    \t");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</thead>\t");
    _builder.newLine();
    _builder.append("  \t");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% @list_");
    Entity _entity = ib.getEntity();
    String _name = _entity.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "    ");
    _builder.append(".each do |");
    Entity _entity_1 = ib.getEntity();
    String _name_1 = _entity_1.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "    ");
    _builder.append("| %>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs_1 = ib.getDataAIOs();
      for(final DataAIO d_1 : _dataAIOs_1) {
        _builder.append("\t\t");
        _builder.append("<td><%= ");
        Entity _entity_2 = ib.getEntity();
        String _name_2 = _entity_2.getName();
        String _lowerCase_2 = _name_2.toLowerCase();
        _builder.append(_lowerCase_2, "\t\t");
        _builder.append(".");
        Attribute _attribute = d_1.getAttribute();
        String _name_3 = _attribute.getName();
        _builder.append(_name_3, "\t\t");
        _builder.append(" %></td>");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      ArrayList<ActionAIO> _actionAIOs_1 = ib.getActionAIOs();
      for(final ActionAIO aio : _actionAIOs_1) {
        {
          if ((aio instanceof ActionAIONavigation)) {
            ActionAIONavigation aio_ = ((ActionAIONavigation) aio);
            _builder.newLineIfNotEmpty();
            _builder.append("<td><a href=\"/");
            _builder.append(this.controllerName, "");
            _builder.append("/");
            InteractionSpace _target = aio_.getTarget();
            String _name_4 = _target.getName();
            String _lowerCase_3 = _name_4.toLowerCase();
            _builder.append(_lowerCase_3, "");
            _builder.append("?param=<%= ");
            Entity _entity_3 = ib.getEntity();
            String _name_5 = _entity_3.getName();
            String _lowerCase_4 = _name_5.toLowerCase();
            _builder.append(_lowerCase_4, "");
            _builder.append(".id %>\">");
            String _text_2 = aio_.getText();
            _builder.append(_text_2, "");
            _builder.append("</a></td>");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% end %>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<br>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence viewRelatedList(final InteractionBlock ib, final InteractionSpace parent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<h3>");
    String _text = ib.getText();
    _builder.append(_text, "");
    _builder.append("</h3>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<table style=\"width:100%; border:1px solid;\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs = ib.getDataAIOs();
      for(final DataAIO d : _dataAIOs) {
        _builder.append("    \t");
        _builder.append("<th>");
        String _text_1 = d.getText();
        String _firstUpper = StringExtensions.toFirstUpper(_text_1);
        _builder.append(_firstUpper, "    \t");
        _builder.append("</th>");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("      ");
    _builder.append("<th colspan=\"");
    ArrayList<ActionAIO> _actionAIOs = ib.getActionAIOs();
    int _size = _actionAIOs.size();
    _builder.append(_size, "      ");
    _builder.append("\"></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% @list_");
    Entity _entity = ib.getEntity();
    String _name = _entity.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "    ");
    _builder.append(".each do |");
    Entity _entity_1 = ib.getEntity();
    String _name_1 = _entity_1.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "    ");
    _builder.append("| %>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs_1 = ib.getDataAIOs();
      for(final DataAIO d_1 : _dataAIOs_1) {
        _builder.append("\t\t");
        _builder.append("<td><%= ");
        Entity _entity_2 = ib.getEntity();
        String _name_2 = _entity_2.getName();
        String _lowerCase_2 = _name_2.toLowerCase();
        _builder.append(_lowerCase_2, "\t\t");
        _builder.append(".");
        Attribute _attribute = d_1.getAttribute();
        String _name_3 = _attribute.getName();
        _builder.append(_name_3, "\t\t");
        _builder.append(" %></td>");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      ArrayList<ActionAIO> _actionAIOs_1 = ib.getActionAIOs();
      for(final ActionAIO aio : _actionAIOs_1) {
        {
          if ((aio instanceof ActionAIONavigation)) {
            ActionAIONavigation aio_ = ((ActionAIONavigation) aio);
            _builder.newLineIfNotEmpty();
            _builder.append("<td><a href=\"/");
            _builder.append(this.controllerName, "");
            _builder.append("/");
            InteractionSpace _target = aio_.getTarget();
            String _name_4 = _target.getName();
            String _lowerCase_3 = _name_4.toLowerCase();
            _builder.append(_lowerCase_3, "");
            _builder.append("?param=<%= ");
            Entity _entity_3 = ib.getEntity();
            String _name_5 = _entity_3.getName();
            String _lowerCase_4 = _name_5.toLowerCase();
            _builder.append(_lowerCase_4, "");
            _builder.append(".id %>\">");
            String _text_2 = aio_.getText();
            _builder.append(_text_2, "");
            _builder.append("</a></td>");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% end %>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<br>");
    _builder.newLine();
    return _builder;
  }
  
  public CharSequence viewEntity(final InteractionBlock ib, final InteractionSpace parent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<h1>");
    String _text = ib.getText();
    _builder.append(_text, "");
    _builder.append("</h1>");
    _builder.newLineIfNotEmpty();
    {
      boolean _or = false;
      ArrayList<ActionAIO> _actionAIOs = ib.getActionAIOs();
      int _size = _actionAIOs.size();
      boolean _equals = (_size == 0);
      if (_equals) {
        _or = true;
      } else {
        ActionAIOOperationType _hasUpdateOrCreateOp = this.hasUpdateOrCreateOp(ib);
        boolean _equals_1 = Objects.equal(_hasUpdateOrCreateOp, null);
        _or = _equals_1;
      }
      if (_or) {
        {
          ArrayList<DataAIO> _dataAIOs = ib.getDataAIOs();
          for(final DataAIO data : _dataAIOs) {
            _builder.append("<p>\t");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<strong>");
            String _text_1 = data.getText();
            String _firstUpper = StringExtensions.toFirstUpper(_text_1);
            _builder.append(_firstUpper, "  ");
            _builder.append("</strong>");
            _builder.newLineIfNotEmpty();
            _builder.append("  ");
            _builder.append("<%= @instance_");
            Entity _entity = ib.getEntity();
            String _name = _entity.getName();
            String _lowerCase = _name.toLowerCase();
            _builder.append(_lowerCase, "  ");
            _builder.append(".");
            Attribute _attribute = data.getAttribute();
            String _name_1 = _attribute.getName();
            _builder.append(_name_1, "  ");
            _builder.append(" %>");
            _builder.newLineIfNotEmpty();
            _builder.append("</p>");
            _builder.newLine();
          }
        }
      } else {
        ActionAIOOperationType aioOp = this.hasUpdateOrCreateOp(ib);
        _builder.newLineIfNotEmpty();
        {
          boolean _equals_2 = Objects.equal(aioOp, ActionAIOOperationType.CallCreateOp);
          if (_equals_2) {
            _builder.append("<%= simple_form_for(@new_");
            Entity _entity_1 = ib.getEntity();
            String _name_2 = _entity_1.getName();
            String _lowerCase_1 = _name_2.toLowerCase();
            _builder.append(_lowerCase_1, "");
            _builder.append(") do |f| %>");
            _builder.newLineIfNotEmpty();
          } else {
            _builder.append("<%= simple_form_for(@instance_");
            Entity _entity_2 = ib.getEntity();
            String _name_3 = _entity_2.getName();
            String _lowerCase_2 = _name_3.toLowerCase();
            _builder.append(_lowerCase_2, "");
            _builder.append(") do |f| %>");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("<%= f.error_notification %>");
        _builder.newLine();
        _builder.append("<div class=\"form-inputs\">");
        _builder.newLine();
        {
          ArrayList<DataAIO> _dataAIOs_1 = ib.getDataAIOs();
          for(final DataAIO data_1 : _dataAIOs_1) {
            {
              boolean _and = false;
              DataAIOType _type = data_1.getType();
              boolean _equals_3 = Objects.equal(_type, DataAIOType.OutputOnly);
              if (!_equals_3) {
                _and = false;
              } else {
                boolean _equals_4 = Objects.equal(aioOp, ActionAIOOperationType.CallUpdateOp);
                _and = _equals_4;
              }
              if (_and) {
                _builder.append("<%= @instance_");
                Entity _entity_3 = ib.getEntity();
                String _name_4 = _entity_3.getName();
                String _lowerCase_3 = _name_4.toLowerCase();
                _builder.append(_lowerCase_3, "");
                _builder.append(".");
                Attribute _attribute_1 = data_1.getAttribute();
                String _name_5 = _attribute_1.getName();
                _builder.append(_name_5, "");
                _builder.append(" %>");
                _builder.newLineIfNotEmpty();
              } else {
                _builder.append("<%= f.input :");
                Attribute _attribute_2 = data_1.getAttribute();
                String _name_6 = _attribute_2.getName();
                _builder.append(_name_6, "");
                _builder.append(", required:true %>");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        {
          Entity _entity_4 = ib.getEntity();
          List<Attribute> _referencedAttributes = _entity_4.referencedAttributes();
          for(final Attribute att : _referencedAttributes) {
            _builder.append("\t");
            DomainModel _domainModel = this.project.getDomainModel();
            String _name_7 = att.getName();
            Entity associatedEntity = _domainModel.getEntityByName(_name_7);
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            List<Attribute> entityAttributes = associatedEntity.getAttributes();
            _builder.newLineIfNotEmpty();
            {
              int _size_1 = entityAttributes.size();
              boolean _greaterThan = (_size_1 > 2);
              if (_greaterThan) {
                _builder.append("\t");
                _builder.append("<%= f.association :");
                String _name_8 = att.getName();
                String _lowerCase_4 = _name_8.toLowerCase();
                _builder.append(_lowerCase_4, "\t");
                _builder.append(",:label_method => lambda { |t| h(t.");
                Attribute _get = entityAttributes.get(0);
                String _name_9 = _get.getName();
                String _lowerCase_5 = _name_9.toLowerCase();
                _builder.append(_lowerCase_5, "\t");
                _builder.append(" + \" \" + t.");
                Attribute _get_1 = entityAttributes.get(1);
                String _name_10 = _get_1.getName();
                String _lowerCase_6 = _name_10.toLowerCase();
                _builder.append(_lowerCase_6, "\t");
                _builder.append(") }, required:true %>");
                _builder.newLineIfNotEmpty();
              } else {
                _builder.append("\t");
                _builder.append("<%= f.association :");
                String _name_11 = att.getName();
                String _lowerCase_7 = _name_11.toLowerCase();
                _builder.append(_lowerCase_7, "\t");
                _builder.append(",label_method: :");
                Attribute _get_2 = entityAttributes.get(0);
                String _name_12 = _get_2.getName();
                String _lowerCase_8 = _name_12.toLowerCase();
                _builder.append(_lowerCase_8, "\t");
                _builder.append(", required:true %>");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        _builder.append("</div>");
        _builder.newLine();
        _builder.append("<div class=\"form-actions\">");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("<%= f.button :submit %>");
        _builder.newLine();
        _builder.append("</div>");
        _builder.newLine();
        _builder.append("<% end %>");
        _builder.newLine();
      }
    }
    return _builder;
  }
  
  public ActionAIOOperationType hasUpdateOrCreateOp(final InteractionBlock interactionBlock) {
    ArrayList<ActionAIO> _actionAIOs = interactionBlock.getActionAIOs();
    for (final ActionAIO aio : _actionAIOs) {
      if ((aio instanceof ActionAIOOperation)) {
        ActionAIOOperation aioOp = ((ActionAIOOperation) aio);
        ActionAIOOperationType _actionAIOOperationType = aioOp.getActionAIOOperationType();
        boolean _equals = Objects.equal(_actionAIOOperationType, ActionAIOOperationType.CallCreateOp);
        if (_equals) {
          return ActionAIOOperationType.CallCreateOp;
        } else {
          ActionAIOOperationType _actionAIOOperationType_1 = aioOp.getActionAIOOperationType();
          boolean _equals_1 = Objects.equal(_actionAIOOperationType_1, ActionAIOOperationType.CallUpdateOp);
          if (_equals_1) {
            return ActionAIOOperationType.CallUpdateOp;
          }
        }
      }
    }
    return null;
  }
  
  public CharSequence viewList(final InteractionBlock ib, final InteractionSpace parent) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<h1>");
    String _text = ib.getText();
    _builder.append(_text, "");
    _builder.append("</h1>");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<table style=\"width:100%; border:1px solid;\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<thead>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs = ib.getDataAIOs();
      for(final DataAIO d : _dataAIOs) {
        _builder.append("    \t");
        _builder.append("<th>");
        String _text_1 = d.getText();
        _builder.append(_text_1, "    \t");
        _builder.append("</th>");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("      ");
    _builder.append("<th colspan=\"");
    ArrayList<ActionAIO> _actionAIOs = ib.getActionAIOs();
    int _size = _actionAIOs.size();
    _builder.append(_size, "      ");
    _builder.append("\"></th>");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</thead>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<tbody>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% @#{");
    Entity _entity = ib.getEntity();
    String _name = _entity.getName();
    String _lowerCase = _name.toLowerCase();
    _builder.append(_lowerCase, "    ");
    _builder.append("}.each do |");
    Entity _entity_1 = ib.getEntity();
    String _name_1 = _entity_1.getName();
    String _lowerCase_1 = _name_1.toLowerCase();
    _builder.append(_lowerCase_1, "    ");
    _builder.append("| %>");
    _builder.newLineIfNotEmpty();
    _builder.append("      ");
    _builder.append("<tr>");
    _builder.newLine();
    {
      ArrayList<DataAIO> _dataAIOs_1 = ib.getDataAIOs();
      for(final DataAIO d_1 : _dataAIOs_1) {
        _builder.append("\t\t");
        _builder.append("<td><%= ");
        Entity _entity_2 = ib.getEntity();
        String _name_2 = _entity_2.getName();
        String _lowerCase_2 = _name_2.toLowerCase();
        _builder.append(_lowerCase_2, "\t\t");
        _builder.append(".");
        Attribute _attribute = d_1.getAttribute();
        String _name_3 = _attribute.getName();
        _builder.append(_name_3, "\t\t");
        _builder.append(" %></td>");
        _builder.newLineIfNotEmpty();
      }
    }
    {
      ArrayList<ActionAIO> _actionAIOs_1 = ib.getActionAIOs();
      for(final ActionAIO aio : _actionAIOs_1) {
        {
          if ((aio instanceof ActionAIONavigation)) {
            ActionAIONavigation aio_ = ((ActionAIONavigation) aio);
            _builder.newLineIfNotEmpty();
            _builder.append("<td><a href=\"/");
            _builder.append(this.controllerName, "");
            _builder.append("/");
            InteractionSpace _target = aio_.getTarget();
            String _name_4 = _target.getName();
            String _lowerCase_3 = _name_4.toLowerCase();
            _builder.append(_lowerCase_3, "");
            _builder.append("?param=<%= ");
            Entity _entity_3 = ib.getEntity();
            String _name_5 = _entity_3.getName();
            String _lowerCase_4 = _name_5.toLowerCase();
            _builder.append(_lowerCase_4, "");
            _builder.append(".id %>\">");
            String _text_2 = aio_.getText();
            _builder.append(_text_2, "");
            _builder.append("</a></td>");
            _builder.newLineIfNotEmpty();
          }
        }
      }
    }
    _builder.append("      ");
    _builder.append("</tr>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<% end %>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</tbody>");
    _builder.newLine();
    _builder.append("</table>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<br>");
    _builder.newLine();
    return _builder;
  }
  
  /**
   * Creates a menu for the application
   */
  public CharSequence createMenu() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("#Menu de navegação");
    _builder.newLine();
    _builder.append("remove_file \'app/views/layouts/_navigation_links.html.erb\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("create_file \'app/views/layouts/_navigation_links.html.erb\' do <<-TEXT");
    _builder.newLine();
    {
      InteractionSpace _mainInteractionSpace = this.project.getMainInteractionSpace();
      MenuBar _menuBar = _mainInteractionSpace.getMenuBar();
      boolean _equals = Objects.equal(_menuBar, null);
      if (_equals) {
        {
          DomainModel _domainModel = this.project.getDomainModel();
          HashMap<String, Entity> _entities = _domainModel.getEntities();
          Collection<Entity> _values = _entities.values();
          for(final Entity e : _values) {
            _builder.append("<%= link_to \'");
            String _name = e.getName();
            String _upperCase = _name.toUpperCase();
            _builder.append(_upperCase, "");
            _builder.append("\', #{");
            String _name_1 = e.getName();
            String _lowerCase = _name_1.toLowerCase();
            _builder.append(_lowerCase, "");
            _builder.append("}_path, class: \'navbar-brand\' %>");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("<li class=\"dropdown\">");
        _builder.newLine();
        _builder.append("   \t");
        _builder.append("<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
        String _upperCase_1 = this.controllerName.toUpperCase();
        _builder.append(_upperCase_1, "   \t");
        _builder.append(" <b class=\"caret\"></b></a>");
        _builder.newLineIfNotEmpty();
        _builder.append("   \t");
        _builder.append("<ul class=\"dropdown-menu\">");
        _builder.newLine();
        {
          List<InteractionSpace> _interactionSpacesWithoutParams = this.project.getInteractionSpacesWithoutParams();
          for(final InteractionSpace is : _interactionSpacesWithoutParams) {
            _builder.append("   \t\t");
            _builder.append("<li><a href=\"/");
            _builder.append(this.controllerName, "   \t\t");
            _builder.append("/");
            String _name_2 = is.getName();
            String _lowerCase_1 = _name_2.toLowerCase();
            _builder.append(_lowerCase_1, "   \t\t");
            _builder.append("\">");
            String _text = is.getText();
            _builder.append(_text, "   \t\t");
            _builder.append("</a></li>");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append(" \t");
        _builder.append("</ul>");
        _builder.newLine();
        _builder.append("</li>");
        _builder.newLine();
      } else {
        {
          InteractionSpace _mainInteractionSpace_1 = this.project.getMainInteractionSpace();
          MenuBar _menuBar_1 = _mainInteractionSpace_1.getMenuBar();
          ArrayList<Menu> _menus = _menuBar_1.getMenus();
          for(final Menu menu : _menus) {
            _builder.append("<li class=\"dropdown\">");
            _builder.newLine();
            _builder.append("\t");
            _builder.append("<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">");
            String _text_1 = menu.getText();
            String _upperCase_2 = _text_1.toUpperCase();
            _builder.append(_upperCase_2, "\t");
            _builder.append(" <b class=\"caret\"></b></a>");
            _builder.newLineIfNotEmpty();
            _builder.append("\t");
            _builder.append("<ul class=\"dropdown-menu\">");
            _builder.newLine();
            {
              ArrayList<MenuItem> _menuItems = menu.getMenuItems();
              for(final MenuItem menuItem : _menuItems) {
                _builder.append("<li><a href=\"/");
                _builder.append(this.controllerName, "");
                _builder.append("/");
                InteractionSpace _target = menuItem.getTarget();
                String _name_3 = _target.getName();
                String _lowerCase_2 = _name_3.toLowerCase();
                _builder.append(_lowerCase_2, "");
                _builder.append("\">");
                InteractionSpace _target_1 = menuItem.getTarget();
                String _text_2 = _target_1.getText();
                _builder.append(_text_2, "");
                _builder.append("</a></li>");
                _builder.newLineIfNotEmpty();
              }
            }
            _builder.append("\t");
            _builder.append("</ul>");
            _builder.newLine();
            _builder.append("</li>");
            _builder.newLine();
          }
        }
      }
    }
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    _builder.newLine();
    _builder.newLine();
    _builder.append("#Menu de navegação");
    _builder.newLine();
    _builder.append("remove_file \'app/views/layouts/_navigation.html.erb\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("create_file \'app/views/layouts/_navigation.html.erb\' do <<-TEXT");
    _builder.newLine();
    _builder.append("<%# navigation styled for Bootstrap 3.0 %>");
    _builder.newLine();
    _builder.append("<nav class=\"navbar navbar-inverse navbar-fixed-top\">");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"navbar-header\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<span class=\"sr-only\">Toggle navigation</span>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<span class=\"icon-bar\"></span>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<span class=\"icon-bar\"></span>");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<span class=\"icon-bar\"></span>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</button>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"collapse navbar-collapse\">");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("<ul class=\"nav navbar-nav\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<%= render \'layouts/navigation_links\' %>");
    _builder.newLine();
    _builder.append("      ");
    _builder.append("</ul>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("  ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</nav>");
    _builder.newLine();
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    return _builder;
  }
  
  /**
   * Updates the application page
   */
  public CharSequence updateApplicationFile() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("# Modifica o esquema da página para permitir o uso de um título personalizado por página");
    _builder.newLine();
    _builder.append("remove_file \'app/views/layouts/application.html.erb\'");
    _builder.newLine();
    _builder.newLine();
    _builder.append("create_file \'app/views/layouts/application.html.erb\' do <<-TEXT");
    _builder.newLine();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<title><%= @title || \"Default Page Title\" %></title>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<meta name=\"description\" content=\"<%= content_for?(:description) ? yield(:description) : \"Default Page Description\" %>\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<%= stylesheet_link_tag \'application\', media: \'all\', \'data-turbolinks-track\' => true %>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<%= javascript_include_tag \'application\', \'data-turbolinks-track\' => true %>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<%= csrf_meta_tags %>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</head>");
    _builder.newLine();
    _builder.append(" \t");
    _builder.append("<body>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<header>");
    _builder.newLine();
    _builder.append("  \t\t\t");
    _builder.append("<%= render \'layouts/navigation\' %>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</header>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<main role=\"main\">");
    _builder.newLine();
    _builder.append("   \t\t\t");
    _builder.append("<%= render \'layouts/messages\' %>");
    _builder.newLine();
    _builder.append("   \t\t\t");
    _builder.append("<%= yield %>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</main>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("TEXT");
    _builder.newLine();
    _builder.append("end");
    _builder.newLine();
    return _builder;
  }
  
  /**
   * Returns the name of all pages (InteractionSpaces) to be generated
   * Devolve o nome de todas as páginas (InteractionSpaces) que vão ser gerados
   */
  public String getPagesNames(final Collection<InteractionSpace> is) {
    String names = "";
    for (final InteractionSpace i : is) {
      String _names = names;
      String _name = i.getName();
      String _lowerCase = _name.toLowerCase();
      String _plus = (" " + _lowerCase);
      names = (_names + _plus);
    }
    return names;
  }
}
